#!/bin/bash

# Скрипт для создания CPIO initramfs из userspace программ
# Использует формат CPIO "newc" (070701)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USERSPACE_DIR="$SCRIPT_DIR/userspace"
HELLO_BIN="$USERSPACE_DIR/hello/target/debug/hello"
INITRAMFS_BIN="$SCRIPT_DIR/initramfs.cpio"
OUTPUT_RUST="$SCRIPT_DIR/hammam/src/initramfs_blob.rs"

# Проверяем, существует ли hello бинарь
if [ ! -f "$HELLO_BIN" ]; then
    echo "Building userspace hello..."
    cd "$USERSPACE_DIR/hello"
    cargo build
    cd "$SCRIPT_DIR"
fi

# Создаем временную директорию с правильной структурой
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

mkdir -p "$TEMP_DIR/bin"
cp "$HELLO_BIN" "$TEMP_DIR/bin/hello"

# Создаем CPIO архив в формате newc
cd "$TEMP_DIR"
find . | cpio -o -H newc > "$INITRAMFS_BIN"
cd "$SCRIPT_DIR"

echo "Created initramfs at: $INITRAMFS_BIN"
echo "Size: $(stat -f%z "$INITRAMFS_BIN" 2>/dev/null || stat -c%s "$INITRAMFS_BIN") bytes"

# Создаем Rust файл с include_bytes!
cat > "$OUTPUT_RUST" << 'EOF'
// Auto-generated by tools/make_initramfs.sh
// Содержит CPIO newc архив с userspace программами

pub const INITRAMFS_CPIO: &[u8] = include_bytes!("../initramfs.cpio");
EOF

echo "Generated Rust blob at: $OUTPUT_RUST"

# Добавляем в main.rs если еще не добавлено
if ! grep -q "mod initramfs_blob" "$SCRIPT_DIR/hammam/src/main.rs"; then
    sed -i.bak '/pub mod vfs;/a\
pub mod initramfs_blob;' "$SCRIPT_DIR/hammam/src/main.rs"
    echo "Added initramfs_blob module to main.rs"
fi
